
# Установка докера
- name: Docker install on WEB1-2
  hosts: web1, web2
  tasks:
  - name: Docker packages download
    shell:
      cmd: "{{item}}"
    loop:
    - sudo apt install apt-transport-https ca-certificates curl software-properties-common
    - wget https://download.docker.com/linux/ubuntu/gpg
    - sudo apt-key add gpg
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - sudo apt install docker-ce
  
  - name: Application run
    shell:
      cmd: "{{item}}"
    loop:
    - docker load < /opt/responding-app.tar
    - docker run --always -p 5000:5000 --ad_ip_addr 192.168.0.2 --db_conn_string postgresql://admin:Passw0rd_@200.100.100.50:5432/admin --external_link ya.ru
    