
# Установка докера
- name: Docker install on WEB1-2
  hosts: web1, web2
  tasks:
  - name: Docker packages download
    package:
     name: apt-transport-https, ca-certificates, curl, software-properties-common
     state: present
     
  - name: Docker repo add
    shell:
      cmd: "{{item}}"
    loop:
    - wget https://download.docker.com/linux/ubuntu/gpg
    - sudo apt-key add gpg
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    
  - name: Docker install
    package:
     name: docker-ce
     state: present
  
  - name: Application load
    shell: docker load < /opt/responding-app.tar
      
  - name: Application run
    copy:
      src: /opt/run.sh
      dest: /opt/run.sh
      owner: root
      group: root
      mode: '0777'
      backup: no
  - name: Application load
    shell: sh /opt/run.sh
  #    docker run --restart=always -p 5000:5000 responding-app --ad_ip_addr 192.168.0.2 --db_conn_string postgresql://admin:Passw0rd_@200.100.100.50:5432/admin --external_link ya.ru